const quoteS = [
'“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”', 
'“There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.”', 
'“I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library.”', 
"'A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.'",
'“In vain have I struggled. It will not do. My feelings will not be repressed. You must allow me to tell you how ardently I admire and love you.”', 
'“I do not want people to be very agreeable, as it saves me the trouble of liking them a great deal.”', 
'“The more I know of the world, the more I am convinced that I shall never see a man whom I can really love. I require so much!”', 
'“It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.”', 
'“There are few people whom I really love, and still fewer of whom I think well. The more I see of the world, the more am I dissatisfied with it; and every day confirms my belief of the inconsistency of all human characters, and of the little dependence that can be placed on the appearance of merit or sense.”', 
'“I cannot fix on the hour, or the spot, or the look or the words, which laid the foundation. It is too long ago. I was in the middle before I knew that I had begun.”', 
'“Angry people are not always wise.”', 
'“I hate to hear you talk about all women as if they were fine ladies instead of rational creatures. None of us want to be in calm waters all our lives.”', 
'“Vanity and pride are different things, though the words are often used synonymously. A person may be proud without being vain. Pride relates more to our opinion of ourselves, vanity to what we would have others think of us.”', 
'“You pierce my soul. I am half agony, half hope...I have loved none but you.”', 
'“but for my own part, if a book is well written, I always find it too short.”', 
'“What are men to rocks and mountains?”', 
'“There is a stubbornness about me that never can bear to be frightened at the will of others. My courage always rises at every attempt to intimidate me.”', 
'“I could easily forgive his pride, if he had not mortified mine.”', 
'“Ah! There is nothing like staying at home, for real comfort.”', 
'“I must learn to be content with being happier than I deserve.”', 
'“If I loved you less, I might be able to talk about it more.”', 
'“The Very first moment I beheld him, my heart was irrevocably gone.”',
'“Silly things do cease to be silly if they are done by sensible people in an impudent way.”', 
'“You are too generous to trifle with me. If your feelings are still what they were last April, tell me so at once. My affections and wishes are unchanged; but one word from you will silence me on this subject for ever.”', 
'“Laugh as much as you choose, but you will not laugh me out of my opinion.”', 
'“Friendship is certainly the finest balm for the pangs of disappointed love.”', 
'“I have not the pleasure of understanding you.”', 
'“I may have lost my heart, but not my self-control. ”', 
'“To be fond of dancing was a certain step towards falling in love”', 
'“I am the happiest creature in the world. Perhaps other people have said so before, but not one with such justice. I am happier even than Jane; she only smiles, I laugh.”', 
'“When I fall in love, it will be forever.”', 
'“From the very beginning— from the first moment, I may almost say— of my acquaintance with you, your manners, impressing me with the fullest belief of your arrogance, your conceit, and your selfish disdain of the feelings of others, were such as to form the groundwork of disapprobation on which succeeding events have built so immovable a dislike; and I had not known you a month before I felt that you were the last man in the world whom I could ever be prevailed on to marry.”', 
'“For what do we live, but to make sport for our neighbors, and laugh at them in our turn?”', 
'“I cannot make speeches, Emma...If I loved you less, I might be able to talk about it more. But you know what I am. You hear nothing but truth from me. I have blamed you, and lectured you, and you have borne it as no other woman in England would have borne it.”', 
'“Give a girl an education and introduce her properly into the world, and ten to one but she has the means of settling well, without further expense to anybody. ”', 
'“I always deserve the best treatment because I never put up with any other.”', 
'“You must learn some of my philosophy. Think only of the past as its remembrance gives you pleasure.”', 
'“You must allow me to tell you how ardently I admire and love you."', 
'“An unhappy alternative is before you, Elizabeth. From this day you must be a stranger to one of your parents. Your mother will never see you again if you do not marry Mr. Collins, and I will never see you again if you do.”', 
'“Till this moment I never knew myself.”', 
'“It is only a novel... or, in short, only some work in which the greatest powers of the mind are displayed, in which the most thorough knowledge of human nature, the happiest delineation of its varieties, the liveliest effusions of wit and humour, are conveyed to the world in the best-chosen language”', 
'“Life seems but a quick succession of busy nothings.”', 
'“I have faults enough, but they are not, I hope, of understanding. My temper I dare not vouch for. It is, I believe, too little yielding— certainly too little for the convenience of the world. I cannot forget the follies and vices of other so soon as I ought, nor their offenses against myself. My feelings are not puffed about with every attempt to move them. My temper would perhaps be called resentful. My good opinion once lost, is lost forever.”', 
'“My good opinion once lost is lost forever.”', 
'“We all know him to be a proud, unpleasant sort of man; but this would be nothing if you really liked him.”', 
'“If I could but know his heart, everything would become easy.”', 
'“There could have been no two hearts so open, no tastes so similar, no feelings so in unison”', 
'“Her heart did whisper that he had done it for her.”', 
'“Seldom, very seldom, does complete truth belong to any human disclosure; seldom can it happen that something is not a little disguised or a little mistaken.”', 
'“A girl likes to be crossed a little in love now and then. It is something to think of”', 
'“The distance is nothing when one has a motive.”', 
'"Perhaps I shall. Yes, yes, if you please, no reference to examples in books. Men have had every advantage of us in telling their own story. Education has been theirs in so much higher a degree; the pen has been in their hands. I will not allow books to prove anything.”', 
'“I wish, as well as everybody else, to be perfectly happy; but, like everybody else, it must be in my own way.”', 
'“Nothing ever fatigues me, but doing what I do not like.”', 
'“Know your own happiness. You want nothing but patience- or give it a more fascinating name, call it hope.”', 
'“What strange creatures brothers are!”', 
'“I have been a selfish being all my life, in practice, though not in principle. As a child I was taught what was right, but I was not taught to correct my temper. I was given good principles, but left to follow them in pride and conceit. Unfortunately an only son (for many years an only child), I was spoilt by my parents, who, though good themselves (my father, particularly, all that was benevolent and amiable), allowed, encouraged, almost taught me to be selfish and overbearing; to care for none beyond my own family circle; to think meanly of all the rest of the world; to wish at least to think meanly of their sense and worth compared with my own. Such I was, from eight to eight and twenty; and such I might still have been but for you, dearest, loveliest Elizabeth! What do I not owe you! You taught me a lesson, hard indeed at first, but most advantageous. By you, I was properly humbled. I came to you without a doubt of my reception. You showed me how insufficient were all my pretensions to please a woman worthy of being pleased.”', 
'“I declare after all there is no enjoyment like reading! How much sooner one tires of anything than of a book!”', 
'“There are people, who the more you do for them, the less they will do for themselves.”', 
'“It is not time or opportunity that is to determine intimacy;—it is disposition alone. Seven years would be insufficient to make some people acquainted with each other, and seven days are more than enough for others.”', 
'“Run mad as often as you choose, but do not faint!”', 
'“Oh, Lizzy! do anything rather than marry without affection.”', 
'“Mary wished to say something very sensible, but knew not how.”', 
'“Nobody can tell what I suffer! But it is always so. Those who do not complain are never pitied.”', 
'“One half of the world cannot understand the pleasures of the other.”', 
'“A woman, especially if she have the misfortune of knowing anything, should conceal it as well as she can.”', 
'“I certainly have not the talent which some people possess," said Darcy, "of conversing easily with those I have never seen before. I cannot catch their tone of conversation, or appear interested in their concerns, as I often see done.”', 
'“How quick come the reasons for approving what we like.”', 
'“...when pain is over, the remembrance of it often becomes a pleasure.”', 
'“Which of all my important nothings shall I tell you first?”', 
'“You must be the best judge of your own happiness.”', 
'“She is tolerable, but not handsome enough to tempt me, and I am in no humor at present to give consequence to young ladies who are slighted by other men.”', 
'“Without music, life would be a blank to me.”', 
'“She was sensible and clever, but eager in everything; her sorrows, her joys, could have no moderation.”', 
'“If adventures will not befall a young lady in her own village, she must seek them abroad.”', 
'“Better be without sense than misapply it as you do. ”', 
'“I come here with no expectations, only to profess, now that I am at liberty to do so, that my heart is and always will be...yours.”', 
'“It would be mortifying to the feelings of many ladies, could they be made to understand how little the heart of a man is affected by what is costly or new in their attire... Woman is fine for her own satisfaction alone. No man will admire her the more, no woman will like her the better for it. Neatness and fashion are enough for the former, and a something of shabbiness or impropriety will be most endearing to the latter.”', 
'“I will be calm. I will be mistress of myself.”', 
'“All the privilege I claim for my own sex (it is not a very enviable one: you need not covet it), is that of loving longest, when existence or when hope is gone!”', 
'“Stupid men are the only ones worth knowing after all.”', 
'“If a book is well written, I always find it too short.”', 
'“Let us never underestimate the power of a well-written letter.”', 
'“Had I been in love, I could not have been more wretchedly blind. But vanity, not love, has been my folly.”', 
'“But people themselves alter so much, that there is something new to be observed in them for ever.”', 
'“A man does not recover from such devotion of the heart to such a woman! He ought not; he does not.”', 
'“I am only resolved to act in that manner, which will, in my own opinion, constitute my happiness, without reference to you, or to any person so wholly unconnected with me.”', 
'“She hoped to be wise and reasonable in time; but alas! Alas! She must confess to herself that she was not wise yet.”', 
'“Elinor agreed to it all, for she did not think he deserved the compliment of rational opposition.”', 
'“I cannot speak well enough to be unintelligible.”', 
'“Time will explain.”', 
'“I never wish to offend, but I am so foolishly shy, that I often seem negligent, when I am only kept back by my natural awkwardness. [...] Shyness is only the effect of a sense of inferiority in some way or other. If I could persuade myself that my manners were perfectly easy and graceful, I should not be shy.”', 
'“There is no charm equal to tenderness of heart.”', 
'“I am determined that only the deepest love will induce me into matrimony. So, I shall end an old maid, and teach your ten children to embroider cushions and play their instruments very ill.”', 
'“I was quiet, but I was not blind.”', 
'“To wish was to hope, and to hope was to expect”', 
'“Her pleasure in the walk must arise from the exercise and the day, from the view of the last smiles of the year upon the tawny leaves and withered hedges, and from repeating to herself some few of the thousand poetical descriptions extant of autumn--that season of peculiar and inexhaustible influence on the mind of taste and tenderness--that season which has drawn from every poet worthy of being read some attempt at description, or some lines of feeling.”', 
'“I am excessively diverted.”', 
'“Now be sincere; did you admire me for my impertinence?"', 
'"For the liveliness of your mind, I did.”', 
'“Now they were as strangers; worse than strangers, for they could never become acquainted.”', 
'“She was convinced that she could have been happy with him, when it was no longer likely they should meet.”', 
'“Follies and nonsense, whims and inconsistencies do divert me, I own, and I laugh at them whenever I can.”', 
'“We have all a better guide in ourselves, if we would attend to it, than any other person can be.”', 
'“Nothing is more deceitful," said Darcy, "than the appearance of humility. It is often only carelessness of opinion, and sometimes an indirect boast.”', 
'“Were I to fall in love, indeed, it would be a different thing; but I have never been in love ; it is not my way, or my nature; and I do not think I ever shall.”', 
'“They were within twenty yards of each other, and so abrupt was his appearance, that it was impossible to avoid his sight. Their eyes instantly met, and the cheeks of each were overspread with the deepest blush. He absolutely started, and for a moment seemed immoveable from surprise; but shortly recovering himself, advanced towards the party, and spoke to Elizabeth, if not in terms of perfect composure, at least of perfect civility.”', 
'“Men of sense, whatever you may choose to say, do not want silly wives.”', 
'“Selfishness must always be forgiven you know, because there is no hope of a cure.”', 
'“Do not consider me now as an elegant female intending to plague you, but as a rational creature speaking the truth from her heart.”', 
'“One word from you shall silence me forever.”' ];

// 


const code = quoteS.forEach((element, index) => {
    console.log(`{id: ${index}, author: 'Jane Austen' , quotes: '${element}'},`);
});


